### ISSUE TITLE
No installation Instruction

### ISSUE THREAD

**Issue by abdel-avalara** [nattatorn-dev/react-native-user-profile#45]
How should I run it ?

**Comment by julianapeace** [comment]
I figured out how to run it. 
1. Git clone the repository.
2. In the repo directory, run `npm install` or `yarn` to install dependencies
3. Run `exp start` to initiate expo. Then, you will see instructions to run a demo on a real device or a simulator. 

Personally, I wasn't able to get it running on a real device. However, I got it running in genymotion  simulating an android API 25. Note: It doesn't work on API 18.

**Comment by nattatorn-dev** [comment]
@julianapeace Many thanks.

**Comment by achilleslinux** [comment]
> 
> 
> I figured out how to run it.
> 
>     1. Git clone the repository.
> 
>     2. In the repo directory, run `npm install` or `yarn` to install dependencies
> 
>     3. Run `exp start` to initiate expo. Then, you will see instructions to run a demo on a real device or a simulator.
> 
> 
> Personally, I wasn't able to get it running on a real device. However, I got it running in genymotion simulating an android API 25. Note: It doesn't work on API 18.
> 
> Edit:
> Got it running on a real android device with the Expo app! Still not working on the iphone though.

Instead of running `exp start`, you have to run `expo start`
