### ISSUE TITLE
Upgrade to at least expo 33

### ISSUE THREAD

**Issue by hannojg** [nattatorn-dev/react-native-user-profile#53]
Hey,
this template project seems unusable to me currently, as it uses expo 27, but the expo client required at least expo SDK version 33. 

Are there any intentions in updating the project? 

Thank you

**Comment by JeroenGoddijn** [comment]
Bump. Please update to at least SDK 33, if not 36.

**Comment by tomhoefer** [comment]
Yes :) I would appreciate an update as well

**Comment by nattatorn-dev** [comment]
I have a bit check Expo spec upgrade, it's a lot of breaking change. react-native, react-navigation. so I will upgrade as soon as possible. Thank you for your feedback

**Comment by nattatorn-dev** [comment]
Now I've upgraded to 38.0.9.
